spring:
  rsocket:
    server:
      port: 7000
      transport: websocket

management:
  endpoint.health.probes.enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

server:
  shutdown: graceful
